[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Patrik Cyvoct <patrik@ptrk.io>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
lazy_static = "1"
regex = "1"
anyhow = "1.0.34"
ndarray = "0.15"
num = "0.4"
